= How to read this report <reading-guide>

The report is in two parts, and they answer different needs.

*Part I, the Grounded Recovery study,* is the confirmatory experiment: the
question, the frozen protocol, the system that implements it, the result, its
trade-offs, and the limits of what it establishes. It is self-contained. A
reader who wants the evidence and nothing else can read Part I and stop.

*Part II, Foundations,* is how the study was built up from nothing. Seven small
deterministic side-studies construct and measure each ingredient in turn: the
simulated world, the formal decision problem, the teacher that produces labels,
the learning paradigm, the policy network, the failure mode that motivates the
whole experiment, and the measurement discipline that makes the answer worth
believing. Each is backed by its own runnable code in `src/gr_foundations/`,
and each ends by pointing at the place in Part I that uses the idea.

The order is deliberate. Part I leads because the result is the point. Part II
follows because a reader who wants to check a premise, or who is meeting
partial observability or intention-to-treat accounting for the first time,
should be able to descend into it rather than wade through it first. Part I
cross-references Part II throughout, so any claim in the study can be traced
down to the small experiment that establishes it.

#block(
  fill: rgb("#fdf3e3"), inset: 8pt, radius: 3pt, width: 100%,
)[
  *Evidence status.* Everything in Part II is exploratory teaching material:
  small sample sizes, no frozen protocol, no confirmatory claims. All
  confirmatory evidence in this report lives in Part I, produced under the
  frozen contract and a single receipted test opening. Where Part I and
  Part II numbers appear to disagree, Part I is the evidence; Part II exists
  to make Part I auditable, not to add claims to it.
]

Every empirical number in either part is generated by code into
`report/generated/` and imported here. None is typed by hand, which is why a
re-analysis cannot leave a sentence quietly stale.
