= The foundations track <foundations-roadmap>

Part I reported the experiment. This part is how it was built up from nothing.

Seven small, deterministic, tested side-studies construct each ingredient in
turn and measure it. The code lives in `src/gr_foundations/` and runs with
`grf run all`; every empirical number below is generated by that code into
`report/generated/foundations/` and imported here, so nothing in this part is
typed by hand either. Each chapter ends with a bridge that names the place in
Part I where the idea is used.

#block(
  fill: rgb("#fdf3e3"), inset: 8pt, radius: 3pt, width: 100%,
)[
  *Evidence status.* Everything in this part is exploratory teaching material:
  small sample sizes, no frozen protocol, no confirmatory claims. All
  confirmatory evidence in this report lives in Part I, produced under the
  frozen contract and a single receipted test opening. Where the two parts
  appear to disagree, Part I is the evidence; this part exists to make Part I
  auditable, not to add claims to it.
]

*The route.* Seven questions, in dependency order:

#table(
  columns: 3,
  [*chapter*], [*question answered*], [*key artifact*],
  [The world], [What is BabyAI, and what does the agent actually see and
    do?], [observation anatomy; world census],
  [Decision processes], [What is a POMDP, why is this one, what would the
    alternatives cost?], [measured perceptual aliasing with conflicting
    oracle labels],
  [Policies and oracles], [What is a policy, what is the oracle, what
    exactly is an expert label?], [policy spectrum; oracle falsification
    attempt],
  [Learning paradigms], [Is this reinforcement learning, and if not, what
    is it?], [from-scratch Q-learning; first cloned policies],
  [The policy network], [What exactly is the architecture, and does every
    piece earn its place?], [generated shape walkthrough; five-way ablation],
  [When cloning breaks], [Why does imitation fail under its own mistakes,
    and what are recovery labels?], [corruption sweep; mini three-arm
    preview],
  [Measuring honestly], [What is intention-to-treat, and why budgets,
    pairing, and freezing?], [bias simulations with known ground truth;
    tamper demonstrations],
)

*The rhythm.* Each chapter moves from intuition to a precise definition, then
to something built and measured, then a common misconception, and finally the
bridge to the study.
