#import "../../generated/foundations/lab05/architecture_facts.typ": *

= The policy network <lab-architecture>

*Intuition.* The model is small enough to hold in one head, at #total-parameters
parameters, and this chapter makes sure of it three ways: a walkthrough
generated from a live instance, a from-scratch reimplementation checked
against the original, and an ablation in which the data judges each design
choice.

*The architecture.* Three embedding tables turn the symbolic observation's
object/color/state indices into vectors (the observation is symbolic, so
embeddings replace the pixel convolutions a visual task would need); two
$3 times 3$ convolutions and a linear projection summarize the $7 times 7$
view. A word-embedding GRU encodes the mission once per episode. Direction
and previous-executed-action embeddings complete the inputs; a fusion layer
mixes everything; a GRU carries memory across steps; a linear head emits
three action logits. The full component table, with parameters and live output
shapes, is generated by instantiating the real model with forward hooks
(`shape_walkthrough`), so the documentation cannot drift from the code. A
from-scratch reimplementation (`gr_foundations.models.LabPolicy`) matches
the study model parameter for parameter; the parity is asserted at runtime
and in tests.

#include "../../generated/foundations/lab05/shape_walkthrough.typ"

*One component removed at a time.* Five variants (the full model, no policy
GRU, no mission input, no previous-action input, and a bag-of-words mission
encoder) trained on identical demonstrations with an identical optimizer,
three seeds each, judged by closed-loop success on unseen scenarios:

#figure(
  image("../../generated/foundations/lab05/figures/ablation_results.svg", width: 100%),
  caption: [Matched ablation (three seeds; whiskers span the seed range).],
)

*Reading the ablation honestly.* At this training scale, clean-condition
success is a blunt instrument: all five variants land within a few points,
with heavily overlapping three-seed ranges, and the same architecture trained
under this chapter and under @lab-learning does not land in the same place
twice. Three-seed comparisons wobble, which is precisely why the study runs six
paired replicates and reports an interval (@lab-measurement). Two
results deserve their own sentences. Removing the mission costs nothing
*here*: with one distractor and a 144-step limit, a mission-blind policy
that tours objects still ends on the right one, because the endpoint tolerates
detours, so language conditioning earns its keep only at tighter horizons or
richer scenes (an interpretation, marked as such). And the bag-of-words
mission encoder matches the GRU at this five-word grammar.

*Why the architecture is still the right one.* The components are justified
by their roles in the study, not by clean-run ablation wins. Memory:
@lab-decision proved no memoryless policy can match the oracle on aliased
states, a structural argument independent of seed noise. Previous-action
input: nearly free in clean conditions, but it is the only channel through
which an externally corrupted execution becomes visible to the policy; its
purpose exists only under @lab-shift's corruptions. Mission conditioning
defines the task. And a recurrent core over a Transformer: the dataset is a
few thousand labelled steps, inference is streamed one observation at a time
with $O(1)$ state, and the model stays small enough to audit by hand, which
this repository treats as a feature.

*Common misconception.* "The ablation with the best number is the right
architecture." At small $n$, ablation deltas smaller than seed noise decide
nothing; design arguments and preregistered endpoints have to carry the
weight the noise cannot.

*Bridge to the study.* `grounded_recovery.model.RecoveryPolicy` is exactly
this architecture; the study adds nothing at model level. Its checkpoints
additionally freeze the vocabulary, action names, and all RNG streams so
training can be resumed or cloned bit-exactly, the cloning that lets three
arms start from the *same* base checkpoint in @lab-shift and in the study.
